### ISSUE TITLE
[DOCUMENTATION] Save single wrong class

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#39]
https://github.com/BenjaminMedia/bonnier-php-sdk/blob/master/indexsearch.md#save-single

Example generates `Fatal error: Class 'Bonnier\Service\IndexSearch\ServiceContent' not found`

I guess that `$item = new \Bonnier\Service\IndexSearch\ServiceContent($username, $secret);`

Should be: `$item = new \Bonnier\IndexSearch\ServiceContent($username, $secret);`

**Comment by skipperbent** [comment]
Thanks for the feedback.

This issue is fixed in version 2.6.
