### ISSUE TITLE
[DOCUMENTATION] Examples missing fields

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#40]
https://github.com/BenjaminMedia/bonnier-php-sdk/blob/master/indexsearch.md#save-single

Examples generates following error:

`Missing required param(s): locale, content_url`

When these two are defined `content_type` also generates an error: `Invalid content-type`

**Comment by skipperbent** [comment]
Thanks for the feedback.

This issue is fixed in version 2.6.
