### ISSUE TITLE
[HELP] IndexSearch update not updating

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#43]
Trying to update a single with the IndexSearch service

https://github.com/BenjaminMedia/bonnier-php-sdk/blob/master/indexsearch.md#update-single

```
$service = new \Bonnier\IndexSearch\ServiceContent($username, $secret);
$service->setDevelopment(true);

$single = $service->getById('6C8064D2B0FC835957C845C4805DF12B');
$single->setDevelopment(true);

$single->title = 'Hello world';
$single->description = 'My new description';

$single->update();
```

After the update `$single` is the same as before and no data has been updated.

Am I doing something wrong here?

**Comment by skipperbent** [comment]
@phh What version of the SDK are you using?

**Comment by phh** [comment]
Seems like I'm only on `"version": "2.5"`. I will try to update and see if it still doesn't update.

**Comment by phh** [comment]
Same thing after update. No update to the single.

**Comment by skipperbent** [comment]
Thanks for the feedback, I've just updated the SDK to fix the issues reported.

Please update your SDK to use the latest version (2.7). I would recommend you adding `"version": "2.*"` in your `composer.json` as version 2 of the SDK is relatively new.

Also you should be able to use the staging server now without calling `setDevelopment(true);` twice:

``` php
$service = new \Bonnier\IndexSearch\ServiceContent($username, $secret);
$service->setDevelopment(true);

$single = $service->getById('6C8064D2B0FC835957C845C4805DF12B');

$single->title = 'Hello world';
$single->description = 'My new description';

$single->update();
```

**Comment by phh** [comment]
Sounds very good! I will try that out tomorrow. Thanks!
