### ISSUE TITLE
[QUESTION] locale - or _ ?

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#44]
Locale example in the documentation are using `_` in locale `da_dk`:

https://github.com/BenjaminMedia/bonnier-php-sdk/blob/master/indexsearch.md#save-single

While every row I'm getting back from the IndexSearch service is using `-` in locale `da-dk`

`public locale -> string(5) "da-dk"`

Should I send/expect a `-` or `_` in locale?

**Comment by phh** [comment]
Getting an error when I'm using `-` so I guess I should use `_` ?

**Comment by skipperbent** [comment]
The IndexSearch API was recently updated so it only support locales with underscore `_`.

Some of the content inside IndexSearch has not been updated and still contain `-`. 

So to answer your question, this would be the correct way of inserting data (it has to be a valid locale though).

`$content->locale = 'en_gb';`

Hope it answers your question :)

**Comment by phh** [comment]
It does - thank you :)
