### ISSUE TITLE
[HELP] TRAPP update not updating

### ISSUE THREAD

**Issue by phh** [BenjaminMedia/bonnier-php-sdk#52]
I'm just getting a save instead of an update. Using following code:

```
$service = new \Bonnier\Trapp\ServiceTranslation($username, $secret);
$service->setDevelopment(true);
$translation = $service->getById('5601679fc01443db5a8b4567');

$translation->setLocale('da_dk');

// Create new field
$field = new \Bonnier\Trapp\Translation\TranslationField('Title', 'Dette er en titel (update)');

// Add this field to a group
$field->setGroup('Titles');

// Create new revision
$revision = new \Bonnier\Trapp\Translation\TranslationRevision();

// Add the field that we created earlier
$revision->addField($field);

$translation->addRevision($revision);

// Add language for the item to be translated into (english, norwegian).
$translation->addLanguage('en_gb');
$translation->addLanguage('nb_no');

$translation->update();
```

**Comment by phh** [comment]
Missing the 2.7.1 update. Hold on.

**Comment by skipperbent** [comment]
The code looks fine - can you please provide me with the version of the SDK you are using?

**Comment by phh** [comment]
`"version": "2.7.1"`

**Comment by skipperbent** [comment]
Thanks... 

I'm not sure that is solves the problem, but I think the Norwegian locale is

`nb_no`

Sorry, I was mistaken - you are already using that.. sorry :)

**Comment by skipperbent** [comment]
Please try to update to version 2.7.3 and see if it resolves the issue.

I found some bugs - and after the fix I was able to save, edit and delete without getting the "locale required" exception.

**Comment by phh** [comment]
Updated the SDK and the exception is gone.

**Comment by phh** [comment]
Closed the wrong ticket. Hold on :)

**Comment by skipperbent** [comment]
I'm keeping my fingers crossed :smile:

**Comment by phh** [comment]
Update works. Brilliant! Thank you :D
